"""Delete mid_name from students

Revision ID: 06d502559373
Revises: 6bd1d0f94e53
Create Date: 2025-03-12 03:52:13.410194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d502559373'
down_revision: Union[str, None] = '6bd1d0f94e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'mid_name')    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('mid_name', sa.String(), nullable=True))
    # ### end Alembic commands ###
