"""Changing column type from volunteer

Revision ID: 9d4b136d938e
Revises: 06d502559373
Create Date: 2025-03-12 03:57:12.701464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4b136d938e'
down_revision: Union[str, None] = '06d502559373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteers', 'phone_number', type_=sa.BigInteger(),postgresql_using="phone_number::bigint")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteers', 'phone_number', type_=sa.String(),postgresql_using="phone_number::text")
    # ### end Alembic commands ###
